### ISSUE TITLE
PlayerInteractEvent Error #1

### ISSUE THREAD

**Issue by Myzumi** [Myzumi/oceanusmc-plugins#2]
Console Error:

```
[14:46:50] [Server thread/ERROR]: Could not pass event PlayerInteractEvent to OceanusMCKitPVP v1.0
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:319) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:589) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:576) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:481) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:448) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:444) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1826) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(SourceFile:31) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.PacketPlayInArmAnimation.a(SourceFile:9) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$0(PlayerConnectionUtils.java:19) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(SourceFile:144) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(SourceFile:118) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:942) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:935) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.awaitTasks(SourceFile:127) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.MinecraftServer.sleepForTick(MinecraftServer.java:919) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:851) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:164) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]
Caused by: java.lang.NullPointerException
	at oceanusmckitpvp.Events.ItemUseEvent.OnItemUse(ItemUseEvent.java:28) ~[?:?]
	at sun.reflect.GeneratedMethodAccessor615.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_275]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:315) ~[server.jar:git-Spigot-ff439d1-ff2b944]
	... 21 more
	```

**Comment by Myzumi** [comment]
Fixed by #5
